language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - sudo apt-get -y install libicu-dev
  - npm install -g npm
script:
  - "npm run-script lint"
notifications:
  irc: "rizon.mibbit.org#dwarf"
